version: '3.10'

services:
  library:
    image: library-ms
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    