"""empty message

Revision ID: 35d4406cbcfd
Revises: bcb9e7bf8275
Create Date: 2024-03-23 19:33:55.724087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d4406cbcfd'
down_revision = 'bcb9e7bf8275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
